task_manager/labels/urls.py
from django.urls import path

from task_manager.labels.views import (
    LabelCreateView,
    LabelDeleteView,
    LabelListView,
    LabelUpdateView,
)

urlpatterns = [
    path('', LabelListView.as_view(), name='labels_list'),
    path('create/', LabelCreateView.as_view(), name='label_create'),
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='label_update'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='label_delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks.views import (
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
)

urlpatterns = [
    path('', TaskListView.as_view(), name='tasks_list'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>', TaskDetailView.as_view(), name='task_detail'),
]

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

task_manager/users/urls.py
from django.urls import path

from task_manager.users.views import (
    UserCreateView,
    UserDeleteView,
    UsersListView,
    UserUpdateView,
)

urlpatterns = [
    path('', UsersListView.as_view(), name='users_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Имя'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Имя'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


class Task(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Имя'
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name='tasks',
        verbose_name='Статус'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='tasks_created',
        verbose_name='Автор'
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='tasks_assigned',
        verbose_name='Исполнитель'
    )
    labels = models.ManyToManyField(
        Label,
        blank=True,
        related_name='tasks',
        verbose_name='Метки'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms

from task_manager.labels.models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Имя',
                }
            ),
        }

task_manager/statuses/forms.py
from django import forms

from task_manager.statuses.models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Имя',
                }
            ),
        }

task_manager/tasks/forms.py
from django import forms

from task_manager.constants import TASK_FIELD_TEXTS
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.models import Task
from task_manager.users.models import User


class BaseTaskFormMixin:
    def __init__(self, field_texts=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        field_texts = field_texts or TASK_FIELD_TEXTS

        for field_name, field in self.fields.items():
            field_config = field_texts.get(field_name, {})

            field.label = field_config.get('label', field.label)
            placeholder = field_config.get('placeholder')

            if placeholder:
                field.widget.attrs['placeholder'] = placeholder

            if field.widget.__class__.__name__ == 'Select':
                field.widget.attrs.setdefault('class', 'form-select')
            field.widget.attrs.setdefault('class', 'form-control')


class TaskForm(BaseTaskFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].queryset = Status.objects.all()
        self.fields['executor'].queryset = User.objects.all()
        self.fields['labels'].queryset = Label.objects.all()

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.constants import ERROR_MESSAGES, SUCCESS_MESSAGES
from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/list.html'
    context_object_name = 'labels'


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('labels_list')
    success_message = SUCCESS_MESSAGES['label']['label_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Создать метку'
        context['submit_button_text'] = 'Создать'
        return context


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('labels_list')
    success_message = SUCCESS_MESSAGES['label']['label_updated']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Изменение метки'
        context['submit_button_text'] = 'Изменить'
        return context


class LabelDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels_list')
    success_message = SUCCESS_MESSAGES['label']['label_deleted']
    error_message = ERROR_MESSAGES['label_using']

    def form_valid(self, form):
        status = self.get_object()
        if status.tasks.exists():
            messages.error(self.request, self.error_message)
            return redirect(self.success_url)
        return super().form_valid(form)

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.constants import ERROR_MESSAGES, SUCCESS_MESSAGES
from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/list.html'
    context_object_name = 'statuses'


class StatusCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('statuses_list')
    success_message = SUCCESS_MESSAGES['status']['status_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Создать статус'
        context['submit_button_text'] = 'Создать'
        return context


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('statuses_list')
    success_message = SUCCESS_MESSAGES['status']['status_updated']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Изменение статуса'
        context['submit_button_text'] = 'Изменить'
        return context


class StatusDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = reverse_lazy('statuses_list')
    success_message = SUCCESS_MESSAGES['status']['status_deleted']
    error_message = ERROR_MESSAGES['status_using']

    def form_valid(self, form):
        status = self.get_object()
        if status.tasks.exists():
            messages.error(self.request, self.error_message)
            return redirect(self.success_url)
        return super().form_valid(form)

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.constants import ERROR_MESSAGES, SUCCESS_MESSAGES
from task_manager.tasks.filter import TaskFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task


class TaskListView(LoginRequiredMixin, FilterView):
    model = Task
    filterset_class = TaskFilter
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('tasks_list')
    success_message = SUCCESS_MESSAGES['task']['task_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Создать задачу'
        context['submit_button_text'] = 'Создать'
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('tasks_list')
    success_message = SUCCESS_MESSAGES['task']['task_updated']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Изменение задачи'
        context['submit_button_text'] = 'Изменить'
        return context


class TaskDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks_list')
    success_message = SUCCESS_MESSAGES['task']['task_deleted']
    error_message = ERROR_MESSAGES['only_author_can_delete']

    def get(self, request, *args, **kwargs):
        task = self.get_object()
        if task.author != request.user and not request.user.is_superuser:
            messages.error(request, self.error_message)
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        if task.author != request.user and not request.user.is_superuser:
            messages.error(request, self.error_message)
            return redirect(self.success_url)
        return super().post(request, *args, **kwargs)

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.constants import ERROR_MESSAGES, SUCCESS_MESSAGES
from task_manager.users.forms import UserCreateForm, UserUpdateForm
from task_manager.users.models import User


class UserPermissionMixin(LoginRequiredMixin):
    error_message = ERROR_MESSAGES['no_permission_update']
    login_required_message = ERROR_MESSAGES['not_authenticated']

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, self.login_required_message)
            return redirect(reverse_lazy('login'))

        if request.user.pk != kwargs.get('pk'):
            messages.error(request, self.error_message)
            return redirect(reverse_lazy('users_list'))

        return super().dispatch(request, *args, **kwargs)


class UsersListView(ListView):
    model = User
    template_name = 'users/list.html'
    context_object_name = 'users'
    paginate_by = 8


class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('login')
    success_message = SUCCESS_MESSAGES['user']['user_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Регистрация'
        context['submit_button_text'] = 'Зарегистрировать'
        return context


class UserUpdateView(UserPermissionMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'base_create_update_form.html'
    success_url = reverse_lazy('users_list')
    success_message = SUCCESS_MESSAGES['user']['user_updated']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Изменение пользователя'
        context['submit_button_text'] = 'Изменить'
        return context


class UserDeleteView(UserPermissionMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users_list')
    success_message = SUCCESS_MESSAGES['user']['user_deleted']

    def form_valid(self, form):
        user = self.get_object()
        if user.tasks_created.exists():
            messages.error(self.request, ERROR_MESSAGES['user_has_tasks'])
            return redirect(self.success_url)
        return super().form_valid(form)


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/auth/login.html'
    redirect_authenticated_user = True
    success_message = SUCCESS_MESSAGES['logged_in']
    error_message = ERROR_MESSAGES['login_invalid']

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


class UserLogoutView(SuccessMessageMixin, LogoutView):
    success_message = SUCCESS_MESSAGES['logged_out']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, self.success_message)
        return super().dispatch(request, *args, **kwargs)

task_manager/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = 'homepage.html'

task_manager/templates/tasks/delete.html
{% extends "base.html" %}

{% block title %}Менеджер задач Hexlet{% endblock %}

{% block content %}
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6">
        <div class="card shadow-sm">
          <div class="card-body">
            <h1 class="h4 mb-2 card-title">Удаление задачи</h1>

            <p>Вы уверены, что хотите удалить {{ task.name }}?</p>

            <form method="post">
              {% csrf_token %}
              <input class="btn btn-danger" type="submit" value="Да, удалить">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}

{% block title %}Менеджер задач Hexlet{% endblock %}

{% block content %}
<div class="container py-4">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card shadow-sm">
        <div class="card-header bg-transparent">
          <div class="d-flex justify-content-between align-items-center">
            <h1 class="h4 mb-0 card-title">Просмотр задачи</h1>
            <span class="badge bg-light text-dark">{{ task.status }}</span>
          </div>
        </div>

        <div class="card-body">
          <div class="mb-4">
            <h2 class="h5 card-title text-primary">Задача: {{ task.name }}</h2>
            {% if task.description %}
              <div class="mt-3 p-3 bg-light rounded border bg-transparent">
                <p class="mb-0">{{ task.description }}</p>
              </div>
            {% endif %}
          </div>

          <div class="row g-3">
            <div class="col-md-6">
              <div class="card h-100 border">
                <div class="card-body">
                  <h3 class="h6 card-subtitle mb-3 text-muted">Детали задачи</h3>
                  <ul class="list-unstyled">
                    <li class="mb-2"><strong>Автор:</strong> {{ task.author.get_full_name|default:task.author }}</li>
                    <li class="mb-2"><strong>Исполнитель:</strong> {{ task.executor.get_full_name|default:task.executor|default:"Не назначен" }}</li>
                    <li><strong>Дата создания:</strong> {{ task.created_at|date:"d.m.Y H:i" }}</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <div class="card h-100 border">
                <div class="card-body">
                  <h3 class="h6 card-subtitle mb-3 text-muted">Метки</h3>
                  {% if task.labels.exists %}
                    <div class="d-flex flex-wrap gap-2">
                      {% for label in task.labels.all %}
                        <span class="badge rounded-pill bg-primary text-light">{{ label }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    <p class="text-muted mb-0">Метки не назначены</p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-footer bg-transparent border-0 mb-2">
          <div class="d-flex justify-content-between">
            <a href="{% url 'tasks_list' %}" class="btn btn-primary">
              <i class="bi bi-arrow-left me-2"></i>Назад к списку
            </a>
            <div class="btn-group">
              <a href="{% url 'task_update' task.id %}" class="btn text-primary px-2" title="Изменить">
                Изменить
              </a>
              <a href="{% url 'task_delete' task.id %}" class="btn text-danger px-2" title="Удалить">
                Удалить
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends "base.html" %}

{% block title %}Менеджер задач Hexlet{% endblock %}

{% block content %}
  <div class="card shadow-sm mt-4">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
      <h1 class="h5 mb-0">
        <i class="fas fa-tags me-1"></i> Задачи
      </h1>
      <a href="{% url 'task_create' %}" class="btn btn-primary">Создать задачу</a>
    </div>
    <form method="get" class="p-3 bg-light rounded shadow-sm">
      <div class="mb-1">
        <label for="id_status" class="form-label">Статус</label>
        {{ filter.form.status }}
      </div>
      <div class="mb-1">
        <label for="id_executor" class="form-label">Исполнитель</label>
        {{ filter.form.executor }}
      </div>
      <div class="mb-2">
        <label for="id_labels" class="form-label">Метка</label>
        {{ filter.form.labels }}
      </div>
      <div class="form-check mb-2">
        {{ filter.form.self_tasks }}
        <label for="id_self_tasks" class="form-check-label">Только свои задачи</label>
      </div>
      <button type="submit" class="btn btn-primary">Показать</button>
    </form>

    <div class="card-body p-0">
      <div class="table-responsive rounded-bottom">
        <table class="table table-striped table-hover mb-0">
          <thead class="table-light">
            <tr class="align-middle">
              <th class="ps-4">ID</th>
              <th>Имя</th>
              <th>Статус</th>
              <th class="text-end">Автор</th>
              <th class="text-end">Исполнитель</th>
              <th class="text-end">Дата создания</th>
              <th class="text-end pe-4"></th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
              <tr class="align-middle">
                <td class="ps-4">{{ task.id }}</td>
                <td>
                  <a href="{% url 'task_detail' task.pk %}" class="text-decoration-none">
                    <i class="fas fa-task-circle me-1 text-muted"></i>
                    {{ task.name }}
                  </a>
                </td>
                <td>{{ task.status.name }}</td>
                <td class="text-end">{{ task.author.first_name }} {{ task.author.last_name }}</td>
                <td class="text-end">{{ task.executor.first_name }} {{ task.executor.last_name }}</td>
                <td class="text-end">{{ task.created_at|date:"d.m.Y H:i" }}</td>
                <td class="text-end pe-4">
                  <div class="btn-group btn-group-sm">
                    <a href="{% url 'task_update' task.pk %}" class="btn text-primary px-2" title="Изменить">
                      Изменить
                    </a>
                    <a href="{% url 'task_delete' task.pk %}" class="btn text-danger px-2" title="Удалить">
                      Удалить
                    </a>
                  </div>
                </td>
              </tr>
            {% empty %}
            <tr>
              <td colspan="7" class="text-center py-4 text-muted">
                <i class="fas fa-info-circle me-2"></i>Задачи не найдены
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}